[server]
headless = true
port = $PORT
enableCORS = false

[theme]
primaryColor = "#FF6347"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"
